name: Trigger Lab Workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: echo "Triggered by: ${{ github.event_name }}"

      - name: Conditional message
        run: |
          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "push" ]; then
            echo "Code was pushed!"
          elif [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            echo "Manual execution"
          elif [ "$EVENT_NAME" = "schedule" ]; then
            echo "Running on schedule"
          else
            echo "Unknown trigger"
          fi
