name: Trigger Lab Workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: echo "Triggered by: ${{ github.event_name }}"

      - name: Conditional message
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "Code was pushed!"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual executions"
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running on schedule"
          else
            echo "Unknown trigger"
          fi
